
const songs = [
`Acid Nation`,
`Adieu`,
`Airfield`,
`All Eyes on the Saint`,
`Anaesthetist`,
`An Ode to Lost Jigsaw Pieces (In Two Movements)`,
`Antwerpen`,
`Anything Can Happen in the Next Half Hour…`,
`apøcaholics anonymøus (main theme in B minor)`,
`Arguing with Thermometers`,
`Common Dreads`,
`Constellations`,
`Crossing The Rubicon`,
`Dear Future Historians…`,
`Destabilise`,
`Elegy For Extinction`,
`Enter Shikari`,
`Empty`,
`Fanfare for the Conscious Man`,
`Fixed Eyes`,
`Frozen Landscape`,
`Gandhi Mate, Gandhi`,
`Gap in the Fence`,
`Havoc A`,
`Havoc B`,
`Hectic`,
`Hello Tyrannosaurus, Meet Tyrannicide`,
`Hoodwinker`,
`Insomnia`,
`Interlude`,
`Jonny Sniper`,
`Juggernauts`,
`Keep It on Ice`,
`Kickin’ Back on the Surface of Your Cheek`,
`Know Your Enemy`,
`Labyrinth`,
`Live Outside`,
`Marionettes (II. The Ascent)`,
`Marionettes (I. The Discovery Of Strings)`,
`…Meltdown`,
`modern living....`,
`Mothership`,
`Myopia`,
`Never Let Go of the Microscope`,
`Nodding Acquaintance`,
`No Sleep Tonight`,
`No Sssweat`,
`OK, Time for Plan B`,
`Pack of Thieves`,
`Quelle Surprise`,
`Rabble Rouser`,
`Radiate`,
`Rat Race`,
`Redshift`,
`Return to Energiser`,
`satellites* *`,
`Score 22`,
`Search Party`,
`Shinrin-yoku`,
`Slipshod`,
`Solidarity`,
`Sorry, You’re Not a Winner`,
`Sssnakepit`,
`Stalemate`,
`Stand Your Ground; This Is Ancient Land`,
`Step Up`,
`Stop the Clocks`,
`Supercharge`,
`System…`,
`Take My Country Back`,
`The Appeal & the Mindsweep I`,
`The Appeal & the Mindsweep II`,
`The Bank of England`,
`The Bearer of Bad News`,
`{ The Dreamer’s Hotel }`,
`The Feast`,
`THE GREAT UNKNOWN`,
`The Jester`,
`thē kĭñg`,
`The Last Garrison`,
`The One True Colour`,
`The Paddington Frisk`,
`the pressure’s on.`,
`There’s a Price on Your Head`,
`The Revolt of the Atoms`,
`The Sights`,
`The Spark`,
`Thumper`,
`T.I.N.A.`,
`Today Won’t Go Down in History`,
`Torn Apart`,
`Tribalism`,
`Undercover Agents`,
`Wall`,
`Waltzing Off The Face Of The Earth (I. Crescendo)`,
`Waltzing off the Face of the Earth (II. Piangevole)`,
`Warm Smiles Do Not Make You Welcome Here`,
`We Can Breathe In Space`,
`When a Jealous Man Finds a Gun`,
`Zzzonked`
]

// module.exports = tracks;
// module.exports = { tracks }


